export const TransportMessageType = Object.freeze({
    PLAYER_ACTION: "PLAYER_ACTION",
    STATE_UPDATED: "STATE_UPDATED",
    CONNECTION_READY: "CONNECTION_READY",
    ACTION_RESULT: "ACTION_RESULT",
    TRANSPORT_ERROR: "TRANSPORT_ERROR"
});
