export const EventTypes = {

    GAME_STARTED:
        "GAME_STARTED",

    GAME_STATE_CHANGED:
        "GAME_STATE_CHANGED",

    ROOM_DISCOVERED:
        "ROOM_DISCOVERED",

    ROOM_ENTERED:
        "ROOM_ENTERED",

    PLAYER_MOVED:
        "PLAYER_MOVED",

    TURN_CHANGED:
        "TURN_CHANGED",

    PLAYER_STAT_CHANGED:
        "PLAYER_STAT_CHANGED",

    HAUNT_TRIGGERED:
        "HAUNT_TRIGGERED",

    PLAYER_CREATED:
        "PLAYER_CREATED",

    PLAYER_REMOVED:
        "PLAYER_REMOVED",

    MAP_UPDATED:
        "MAP_UPDATED",

    ROOM_REVEALED:
        "ROOM_REVEALED",

    CARD_DRAW_REQUESTED:
        "CARD_DRAW_REQUESTED",

    CARD_DRAWN:
        "CARD_DRAWN",

    CARD_EFFECT_REQUESTED:
        "CARD_EFFECT_REQUESTED",

    CARD_EFFECT_RESOLVED:
        "CARD_EFFECT_RESOLVED",

    OMEN_DRAWN:
        "OMEN_DRAWN",

    HAUNT_ROLL_REQUESTED:
        "HAUNT_ROLL_REQUESTED",

    HAUNT_ROLL_COMPLETED:
        "HAUNT_ROLL_COMPLETED",

    SAVE_GAME_REQUESTED:
        "SAVE_GAME_REQUESTED",

    GAME_SAVED:
        "GAME_SAVED",

    LOAD_GAME_REQUESTED:
        "LOAD_GAME_REQUESTED",

    GAME_LOADED:
        "GAME_LOADED",

    SCENARIO_STARTED:
        "SCENARIO_STARTED",

    SCENARIO_UPDATED:
        "SCENARIO_UPDATED",

    SCENARIO_COMPLETED:
        "SCENARIO_COMPLETED",

    SCENARIO_RUNTIME_CREATED:
        "SCENARIO_RUNTIME_CREATED",

    SCENARIO_RUNTIME_UPDATED:
        "SCENARIO_RUNTIME_UPDATED",

    TRAITOR_ASSIGNMENT_REQUESTED:
        "TRAITOR_ASSIGNMENT_REQUESTED",

    TRAITOR_ASSIGNED:
        "TRAITOR_ASSIGNED",

    GAME_ENDED:
        "GAME_ENDED",

    INFORMATION_ROUTED:
        "INFORMATION_ROUTED"
};


