export const EventTypes = {

    GAME_STARTED:
        "GAME_STARTED",

    GAME_STATE_CHANGED:
        "GAME_STATE_CHANGED",

    ROOM_DISCOVERED:
        "ROOM_DISCOVERED",

    ROOM_ENTERED:
        "ROOM_ENTERED",

    PLAYER_MOVED:
        "PLAYER_MOVED",

    TURN_CHANGED:
        "TURN_CHANGED",

    PLAYER_STAT_CHANGED:
        "PLAYER_STAT_CHANGED",

    HAUNT_TRIGGERED:
        "HAUNT_TRIGGERED",

    PLAYER_CREATED:
        "PLAYER_CREATED",

    PLAYER_REMOVED:
        "PLAYER_REMOVED",

    MAP_UPDATED:
        "MAP_UPDATED",

    ROOM_REVEALED:
        "ROOM_REVEALED",

    CARD_DRAW_REQUESTED:
        "CARD_DRAW_REQUESTED",

    CARD_DRAWN:
        "CARD_DRAWN"
};


