export const LobbyMessageType = Object.freeze({
    CLIENT_ASSIGNED: "CLIENT_ASSIGNED",
    CREATE_ROOM: "CREATE_ROOM",
    ROOM_CREATED: "ROOM_CREATED",
    JOIN_ROOM: "JOIN_ROOM",
    ROOM_JOINED: "ROOM_JOINED",
    ROOM_REJECTED: "ROOM_REJECTED",
    PEER_CONNECTED: "PEER_CONNECTED",
    PEER_DISCONNECTED: "PEER_DISCONNECTED",
    RESUME_ROOM: "RESUME_ROOM",
    ROOM_RESUMED: "ROOM_RESUMED",
    RESUME_REJECTED: "RESUME_REJECTED"
});

export const SessionControlMessageType = Object.freeze({
    ACTIVATE_SESSION: "ACTIVATE_SESSION",
    SESSION_STARTED: "SESSION_STARTED",
    PLAYER_BINDING_ASSIGNED: "PLAYER_BINDING_ASSIGNED",
    SESSION_CLOSED: "SESSION_CLOSED",
    PEER_RECONNECTING: "PEER_RECONNECTING",
    PEER_RESUMED: "PEER_RESUMED",
    RESUME_SESSION: "RESUME_SESSION",
    SESSION_RESUMED: "SESSION_RESUMED",
    RESUME_FAILED: "RESUME_FAILED"
});

export const LobbyErrorCode = Object.freeze({
    ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
    ROOM_FULL: "ROOM_FULL",
    ROOM_CLOSED: "ROOM_CLOSED",
    ALREADY_IN_ROOM: "ALREADY_IN_ROOM",
    NOT_HOST: "NOT_HOST",
    SESSION_ALREADY_STARTED: "SESSION_ALREADY_STARTED",
    INVALID_REQUEST: "INVALID_REQUEST",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    ROOM_NOT_RECONNECTING: "ROOM_NOT_RECONNECTING",
    ALREADY_CONNECTED: "ALREADY_CONNECTED",
    STALE_CONNECTION: "STALE_CONNECTION"
});
