export const LobbyMessageType = Object.freeze({
    CLIENT_ASSIGNED: "CLIENT_ASSIGNED",
    CREATE_ROOM: "CREATE_ROOM",
    ROOM_CREATED: "ROOM_CREATED",
    JOIN_ROOM: "JOIN_ROOM",
    ROOM_JOINED: "ROOM_JOINED",
    ROOM_REJECTED: "ROOM_REJECTED",
    PEER_CONNECTED: "PEER_CONNECTED",
    PEER_DISCONNECTED: "PEER_DISCONNECTED"
});

export const SessionControlMessageType = Object.freeze({
    ACTIVATE_SESSION: "ACTIVATE_SESSION",
    SESSION_STARTED: "SESSION_STARTED",
    PLAYER_BINDING_ASSIGNED: "PLAYER_BINDING_ASSIGNED",
    SESSION_CLOSED: "SESSION_CLOSED"
});

export const LobbyErrorCode = Object.freeze({
    ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
    ROOM_FULL: "ROOM_FULL",
    ROOM_CLOSED: "ROOM_CLOSED",
    ALREADY_IN_ROOM: "ALREADY_IN_ROOM",
    NOT_HOST: "NOT_HOST",
    SESSION_ALREADY_STARTED: "SESSION_ALREADY_STARTED",
    INVALID_REQUEST: "INVALID_REQUEST"
});
